CREATE OR REPLACE TRIGGER HELLO_WORLD6 
AFTER DELETE
ON STUDENTS
FOR EACH ROW 
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Hello World 6');
END;

DELETE FROM STUDENTS 
WHERE STUDENT_NAME LIKE '%n';

--Problem Example 1
CREATE TABLE LOG_TABLE_CGPA_UPDATE
(
USERNAME VARCHAR2(25),
DATETIME DATE
);

CREATE OR REPLACE TRIGGER LOG_CGPA_UPDATE
AFTER UPDATE
OF CGPA 
ON STUDENTS
DECLARE
	USERNAME VARCHAR2(25);
BEGIN
	USERNAME := USER;
	
	INSERT INTO LOG_TABLE_CGPA_UPDATE
	VALUES(USERNAME, SYSDATE);
END;

UPDATE STUDENTS SET CGPA = CGPA - 0.01;

--Problem Example 2
CREATE TABLE STUDENTS_DELETED
(
	STUDENT_NAME VARCHAR2(25),
	CGPA NUMBER,
	USERNAME VARCHAR2(25),
	DATETIME DATE
);

CREATE OR REPLACE TRIGGER BACKUP_DELETED_STUDENTS
BEFORE DELETE
ON STUDENTS
FOR EACH ROW
DECLARE
	D_STUDENT_NAME VARCHAR(25);
	D_CGPA NUMBER;
	USERNAME VARCHAR2(25);
	DATETIME DATE;
BEGIN
	D_STUDENT_NAME := :OLD.STUDENT_NAME;
	D_CGPA := :OLD.CGPA;
	USERNAME := USER;
	DATETIME := SYSDATE;
	
	INSERT INTO STUDENTS_DELETED
	VALUES(D_STUDENT_NAME, D_CGPA, USERNAME, DATETIME);
END;

DELETE FROM STUDENTS WHERE CGPA < 3.85 ;

SELECT * FROM STUDENTS_DELETED;

--Practice
CREATE TABLE LOW_CGPA_STUDENTS
(
	STUDENT_NAME VARCHAR2(25)
);

CREATE OR REPLACE TRIGGER SAVE_LOW_CGPA_STUDENTS
BEFORE UPDATE OR INSERT
OF CGPA
ON STUDENTS
FOR EACH ROW
DECLARE
	L_STUDENT_NAME VARCHAR2(25);
	CGPA NUMBER;
BEGIN
	L_STUDENT_NAME := :NEW.STUDENT_NAME;
	CGPA := :NEW.CGPA;
	
	IF CGPA < 2.0 THEN
		INSERT INTO LOW_CGPA_STUDENTS VALUES(L_STUDENT_NAME);
	END IF;
END;

INSERT INTO STUDENTS VALUES('Mokhra', 1.5);
UPDATE STUDENTS
SET CGPA = 1.5
WHERE STUDENT_NAME = 'Showvik';

UPDATE STUDENTS
SET STUDENT_NAME = 'Nazmul'
WHERE STUDENT_NAME = 'Anonto';

SELECT * FROM LOW_CGPA_STUDENTS;

--Problem Example 3
CREATE OR REPLACE TRIGGER CORRECT_STUDENT_NAME 
BEFORE UPDATE OR INSERT
OF STUDENT_NAME 
ON STUDENTS
FOR EACH ROW
DECLARE
BEGIN
	:NEW.STUDENT_NAME := INITCAP(:NEW.STUDENT_NAME);
END;

INSERT INTO STUDENTS VALUES ('SHAkil ahMED', 3.80);
INSERT INTO STUDENTS VALUES ('masum billah', 3.60);

--Practice
CREATE OR REPLACE TRIGGER INVALID_NAME 
BEFORE INSERT OR UPDATE
OF STUDENT_NAME 
ON STUDENTS
FOR EACH ROW
DECLARE
BEGIN
	IF REGEXP_INSTR(:NEW.STUDENT_NAME, '[[:digit:]]') <> 0 THEN
		raise_application_error(-20001, 'INVALID NAME: Name contains digit/s');
	END IF;
END;

DELETE FROM STUDENTS
WHERE STUDENT_NAME = 'A9ngon';
INSERT INTO STUDENTS VALUES('A9ngon', 4.00);