--A
SELECT MANAGER_ID, COUNT(EMPLOYEE_ID) MANAGES
FROM EMPLOYEES
GROUP BY MANAGER_ID;

--B
SELECT DEPARTMENT_ID, COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
WHERE SALARY > 30000
GROUP BY DEPARTMENT_ID;

--C
SELECT DEPARTMENT_ID, MIN(SALARY) MIN_SALARY, MAX(SALARY) MAX_SALARY, AVG(SALARY) AVG_SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID <> 80
GROUP BY DEPARTMENT_ID
ORDER BY AVG_SALARY DESC, MAX_SALARY DESC, MIN_SALARY DESC;