CREATE OR REPLACE FUNCTION ISNUMBER(VAL IN VARCHAR2)
RETURN VARCHAR2 IS
	N NUMBER;
BEGIN
	N := TO_NUMBER(VAL);
	RETURN 'YES';
	
EXCEPTION
	WHEN VALUE_ERROR THEN
		RETURN 'NO';
END;

BEGIN
	DBMS_OUTPUT.PUT_LINE(ISNUMBER('1B0'));
END;