SELECT (TRUNC((SALARY / 5000), 0) * 5000 + 5000) AS SALARY_GROUP, COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY (TRUNC((SALARY / 5000), 0) * 5000 + 5000)
ORDER BY SALARY_GROUP ASC;

SELECT TO_CHAR(HIRE_DATE, 'YYYY') AS "HIRE YEAR", JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'YYYY'), JOB_ID
ORDER BY JOB_ID, "HIRE YEAR";