--A
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
											 FROM DEPARTMENTS
											 WHERE DEPARTMENT_NAME = 'Sales');

--B
SELECT LAST_NAME, SALARY
FROM EMPLOYEES 
WHERE SALARY > ANY (SELECT SALARY
										FROM EMPLOYEES
										WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
																					 FROM DEPARTMENTS
																					 WHERE DEPARTMENT_NAME = 'Sales'));

--C																					 
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > ALL (SELECT SALARY
										FROM EMPLOYEES
										WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
																					 FROM DEPARTMENTS
																					 WHERE DEPARTMENT_NAME = 'Sales'));
				
--D																			 
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN (SELECT (AVG(SALARY) - 5000)
								FROM EMPLOYEES
								WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
																			 FROM DEPARTMENTS
																			 WHERE DEPARTMENT_NAME = 'Sales'))
AND (SELECT (AVG(SALARY) + 5000)
								FROM EMPLOYEES
								WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
																			 FROM DEPARTMENTS
																			 WHERE DEPARTMENT_NAME = 'Sales'));