--a
SELECT EMPLOYEE_ID
FROM EMPLOYEES
MINUS
(SELECT MANAGER_ID
FROM EMPLOYEES);
--b
SELECT LAST_NAME
FROM EMPLOYEES
MINUS
(SELECT DISTINCT E2.LAST_NAME
FROM EMPLOYEES E1 JOIN EMPLOYEES E2 ON(E1.MANAGER_ID = E2.EMPLOYEE_ID));
--c
SELECT LOCATION_ID
FROM LOCATIONS
MINUS
(SELECT LOCATION_ID
FROM DEPARTMENTS)