BEGIN
-- 	DBMS_OUTPUT.PUT_LINE(SYSDATE);
	FOR R IN (SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM EMPLOYEES)
	LOOP
		IF R.HIRE_DATE = SYSDATE THEN
			DBMS_OUTPUT.PUT_LINE('Happy Anniversary ' || R.FIRST_NAME || ' ' || R.LAST_NAME);
		END IF;
	END LOOP;
END;